# -*- coding: utf-8 -*-
"""fake-news-detector.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M1WFSWawxBXY-e9ZKB7Dc6thkJF1Rd2P
"""

import pandas as pd
import numpy as np
import re
import string

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

# 1️⃣ تحميل البيانات
fake_df = pd.read_csv("/content/sample_data/Fake.csv")
true_df = pd.read_csv("/content/sample_data/True.csv")

# إضافة العمود label (1 = مزيف، 0 = حقيقي)
fake_df['label'] = 1
true_df['label'] = 0

# دمج البيانات
df = pd.concat([fake_df, true_df], axis=0).sample(frac=1).reset_index(drop=True)
print("✅ حجم البيانات:", df.shape)

# نستخدم فقط النصوص
df['content'] = df['title'] + " " + df['text']

# 2️⃣ تنظيف النصوص
def clean_text(text):
    if isinstance(text, str):
        text = text.lower()
        text = re.sub(r'https?://\S+|www\.\S+', '', text)  # حذف الروابط
        text = text.translate(str.maketrans('', '', string.punctuation))  # حذف الرموز
        text = re.sub(r'\d+', '', text)  # حذف الأرقام
        text = re.sub(r'\s+', ' ', text).strip()
        return text
    return ""

df['content'] = df['content'].apply(clean_text)

# 3️⃣ تقسيم البيانات
X_train, X_test, y_train, y_test = train_test_split(
    df['content'], df['label'], test_size=0.2, random_state=42, stratify=df['label']
)

# 4️⃣ تحويل النصوص إلى تمثيل عددي باستخدام TF-IDF
vectorizer = TfidfVectorizer(max_features=5000, stop_words='english')
X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

# 5️⃣ تدريب نموذج ML
model = LogisticRegression(max_iter=300)
model.fit(X_train_tfidf, y_train)

# 6️⃣ التقييم
y_pred = model.predict(X_test_tfidf)
print("✅ الدقة:", accuracy_score(y_test, y_pred))
print("✅ تقرير التصنيف:\n", classification_report(y_test, y_pred))

# ✅ اختبار يدوي
test_news = [
    "Breaking news: Scientists discover a new cure for cancer that will change the world!",
    "NASA confirms alien spaceship has landed in New York!"
]

test_news_clean = [clean_text(news) for news in test_news]
test_vec = vectorizer.transform(test_news_clean)
predictions = model.predict(test_vec)

for news, pred in zip(test_news, predictions):
    print(f"خبر: {news[:50]}... → {'مزيف' if pred==1 else 'حقيقي'}")